package com.franza.UP.ac;

import java.util.List;

import javax.servlet.http.HttpServletRequest;

import com.franza.UP.bean.JavaBean;
import com.franza.UP.to.TO;
import com.franza.UP.util.InvalidInputException;

/**
 * <p> Non-instantiable class that contains all the signatures for operations further implemented in the application controller classes. </p>
 */
public abstract class AC {

	/**
	 * <p> Object that represents the bean used to carry out operations. </p> 
	 * <p> It can be local or remote, according to how it is defined in the servlet.</p>
	 */
	protected JavaBean bean;
	
	/**
	 * <p> Abstract signature of a method that carries out operations using the data given in input by the user and acquired through the servlet. <p>
	 * @param req : servlet request that contains variables and data filled by the user.
	 * @param operation : string that contains the value of the operation to be carried out.
	 * @return the instance of the application controller.
	 * @throws InvalidInputException Exception thrown when one or more inputs given by the user are not valid. It is generated by the operations of the instantiated bean.
	 */
	public abstract List<TO> handleOperation(HttpServletRequest req, String operation) throws InvalidInputException;

	/**
	 * <p> Getter method for the instantiated java bean: provides the value of the stored java bean. </p>
	 * @return the java bean to be provided.
	 */
	public JavaBean getBean() {
		return bean;
	}

	/**
	 * <p> Setter method for the instantiated java bean: sets the value of the java bean given in input. </p>
	 * @param bean : java bean to be set.
	 * @return the instance of the application controller.
	 */
	public AC setBean(JavaBean bean) {
		this.bean = bean;
		return this;
	}


}