package com.franza.UP.ac;

import java.util.List;

import javax.servlet.http.HttpServletRequest;

import com.franza.UP.to.DealerTO;
import com.franza.UP.to.TO;
import com.franza.UP.util.InvalidInputException;

/**
 * <p> Instantiable class that extends the abstract Application Controller class</p>
 */
public class DealerAC extends AC {
	
	/**
	 * <p> Implementation of a method that calls the java bean functions according to the user's input and the selected operation on the entity dealer. </p>
	 * <p> CRUD operations are given by default.</p>
	 * @param req : servlet request that contains variables and data filled by the user.
	 * @param operation : string that contains the value of the operation to be carried out.
	 * @return the instance of the application controller.
	 * @throws InvalidInputException Exception thrown when one or more inputs given by the user are not valid. It is generated by the operations of the instantiated bean.
	 */
	public List<TO> handleOperation(HttpServletRequest req, String operation) throws InvalidInputException {
		List<TO> list = null;

		switch (operation) {
			case "create_dealer": {
				list = bean.create(new DealerTO().getFromRequest(req)); 
				break;
			}
			case "read_dealer": {
				list = bean.read(new DealerTO().getFromRequest(req).searchAdjust()); 
				break;
			}
			case "update_dealer": {
				list = bean.update(new DealerTO().getFromRequest(req).checkKeys()); 
				break;
			}
			case "delete_dealer": {
				list = bean.delete(new DealerTO().getFromRequest(req).checkPrimaryKeys()); 
				break;
			}
			default: {
				list = bean.read(new DealerTO().getFromRequest(req));
			}
		}
		return list;

	}

}
