package com.franza.UP.ac;

import java.util.List;

import javax.servlet.http.HttpServletRequest;

import com.franza.UP.to.WeeklyReportTO;
import com.franza.UP.to.TO;
import com.franza.UP.util.InvalidInputException;

/**
 * <p> Instantiable class that extends the abstract Application Controller class</p>
 */
public class WeeklyReportAC extends AC {
		
	/**
	 * <p> Implementation of a method that calls the java bean functions according to the user's input and the selected operation on the entity weeklyReport. </p>
	 * <p> CRUD operations are given by default.</p>
	 * @param req : servlet request that contains variables and data filled by the user.
	 * @param operation : string that contains the value of the operation to be carried out.
	 * @return the instance of the application controller.
	 * @throws InvalidInputException Exception thrown when one or more inputs given by the user are not valid. It is generated by the operations of the instantiated bean.
	 */
	public List<TO> handleOperation(HttpServletRequest req, String operation) throws InvalidInputException {
		List<TO> list = null;

		switch (operation) {
			case "produce_weeklyReport": {
				list = bean.create(new WeeklyReportTO().getFromRequest(req)); 
				break;
			}
			case "read_weeklyReport": {
				list = bean.read(new WeeklyReportTO().getFromRequest(req)); 
				break;
			}
			default: {
				list = bean.read(new WeeklyReportTO().getFromRequest(req));
			}
		}
		return list;

	}
	
}
